### ISSUE TITLE
Quotes for .env file values are included in interpolation

### ISSUE THREAD

**Issue by ajcrites** [danday74/envsub#10]
If you have a `.env` file like this:

```
NAME="Value"
```

running `envsub --env-file .env` results in a substitution of `${NAME}` for `"Value"`.

However, running `NAME="Value" envsub` results in `Value` (not wrapped in quotes).

I think that quotes should be ignored when setting values from a key=value file as you might expect when sourcing the file in a shell environment.

**Comment by danday74** [comment]
Given the increase in downloads on this module I am planning to be more active - will investigate this issue and get back to you

**Comment by danday74** [comment]
This is fixed in 4.0.2 - closing
