### ISSUE TITLE
Ignore undefined variables

### ISSUE THREAD

**Issue by shamasis** [danday74/envsub#2]
Great module.

I have a simple question - in order to be near compatible with envsubst, I was wondering if we could configure this to not replace template where variable is not found.

For example, if `{{var1}}` is not defined in environment, it remains as `{{var1}}` unlike the present behaviour, which simply removes this string.

**Comment by danday74** [comment]
thanks for feedback - yes i will make changes to support your suggestion - expect these changes to be available in approx 1 week

**Comment by shamasis** [comment]
I am so glad to hear that. I can help if you want me too. From what I see your approach is to use handlebars.

Problem is that handlebars totally does not have the feature we are discussing here and this may become very challenging.

**Comment by danday74** [comment]
i always aim to keep it simple. this is the approach i am taking ...

envsub templateFile outputFile (replaces all env vars, behaviour unchanged)

envsub --env MYVAR1 templateFile outputFile (substitues only MYVAR1 if it appears)

envsub --env MYVAR1 --env MYVAR2=hello templateFile outputFile (substitues both vars given and provides a value for MYVAR2 - this is taken from the docker approach to env vars)

how does this sound?

**Comment by danday74** [comment]
> Problem is that handlebars totally does not have the feature we are discussing here and this may become very challenging.

Have hit probs with use of Handlebars.

I suggest that envsub exposes two bin commands ..

envsubh (retains current behvaiour with Handlebars templating, no option to only parse some vars)

envsub ... 

envsub templateFile outputFile (switches to use of ${VAR} syntax as used by envsubst, no handlebars templating, default is to attempt to substitute all vars)

envsub --env MYVAR1 --env MYVAR2=hello templateFile outputFile .. same as previous but only attempts to substitute vars given

**Comment by danday74** [comment]
update - i am working on this, have overshot the expected one week goal. This is because I could not get handlebars to reliably do the ignore, so had to rewrite a lot more than expected.

**Comment by shamasis** [comment]
Your idea is brilliant and simple. I had a hunch that ignoring would be tough in handlebars.

**Comment by shamasis** [comment]
Though I have a point - this idea will require people to have prior knowledge of the variables they need to replace. If you ask me, just adding a switch to ignore variables not found is easiest for users.

In both cases, the trick is to make handlebars ignore replacements. That even I'm not sure how to do without digging deep.

**Comment by shamasis** [comment]
My use case is simple. I have a system which already does the thing you mentioned above. But I want to replace all the one defined in environment first and then pass the file to this system so that any custom ones are replaced. envsubst is not easy to procure cross platform. Hence the request.

**Comment by danday74** [comment]
> just adding a switch to ignore variables not found is easiest for users

Agreed, now have the following switches ..

-p, --protect .. protect non-existent environment variables from being replaced
-e, --env .. example --env VAR1 --env VAR2=hello
  this will substitue VAR1 and VAR2 (VAR2 is substituted with hello)
-s, --syntax .. one of default|dollar-basic|dollar-curly|dollar-both|handlebars

  default expects .. see dollar-curly
  dollar-basic expects .. $MYVAR
  dollar-curly expects .. ${MYVAR}
  dollar-both expects .. $MYVAR or ${MYVAR}
  handlebars expects .. {{ MYVAR }}

This last flag describes the replacement syntax to use in the template.

I expect dev complete in one more week. Unit testing is complete but still a fair bit of tidying up to do, testing inside a docker container, etc

**Comment by danday74** [comment]
i appreciate the only flag you really need is --protect but I have added the others to support the wider community .. for example ..

use of --protect will only replace env vars that exist ..

use of --protect --env VAR1 --env VAR2 --env VAR3=something .. will only replace VAR1 and VAR2 if they exist

**Comment by danday74** [comment]
still working on this - unit testing taking longer than expected - very thorough unit testing - completion expected in 2 or 3 days

**Comment by danday74** [comment]
go live is imminent - coding and testing is complete - working on the documentation

**Comment by danday74** [comment]
Just published v3.0.0 (which is not backwards compatible with previous versions) with the major changes discussed herein - everything fully working and tested.

README is still tatty and needs polishing. Will re-publish after I have tidied the README and will then close this issue.

**Comment by danday74** [comment]
v3.0.4 released which simply updates the README documentation. A few further minor tweaks to docs may follow. However, I feel that this issue is now resolved.

To use as per your requirement not to substitute non-existent vars simply do ..

envsub --protect templateFile outputFile

The default template syntax is now ${MYVAR}

If you prefer {{MYVAR}} then do ..

envsub --protect --syntax handlebars templateFile outputFile

You will need to update envsub to the latest version. God bless and I hope this satisfies your needs.

If there are any further issues please raise them. I would expect a much quicker turnaround next time since this change required a total rewrite. Apologies for the delay.

Closing!
