### ISSUE TITLE
Support stdout

### ISSUE THREAD

**Issue by ilyabo** [danday74/envsub#4]
This could be a very useful utility for us. Unfortunately, it doesn't support writing the result to stdout which prevents us from using it. Could you consider adding an option for it?

**Comment by danday74** [comment]
I can review the effort needed to do this, if its not too much I can implement - when do you need it done by? rough estimate is fine

**Comment by ilyabo** [comment]
Thanks! I went for envhandlebars for now which does support stdin, so no hurry. Just thought it could be useful for others too.

**Comment by danday74** [comment]
If there's more demand for this I will fix it.

**Comment by danday74** [comment]
Now that this module is more popular, I am willing to put the effort in to fix this. However, I only plan to do so if there is more demand.

Does anyone else want this fixed? If so let me know and I will crack on with it.

Leaving open for now.

**Comment by danday74** [comment]
This is fixed in 4.0.4
